version: '3.8'
services:
 web:
  build: .
  command: python /pee/manage.py runserver 0.0.0.0:8000
  volumes:
  - .:/pee
  ports:
  - 8000:8000
  depends_on:
    - db
 db:
  image: postgres
  volumes:
   - postgres_data:/var/lib/postgresql/data/
  ports:
   - 5432:5432


  environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
 postgres_data:
